name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    name: Build and Release for macOS
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Run tests
        run: cargo test --verbose

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create archive
        run: |
          cd target/${{ matrix.target }}/release
          tar -czf fdml-${{ matrix.target }}.tar.gz fdml
          mv fdml-${{ matrix.target }}.tar.gz ../../../

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fdml-${{ matrix.target }}
          path: fdml-${{ matrix.target }}.tar.gz

  create-release:
    name: Create GitHub Release
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          
          # Create release
          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "Release $VERSION of FDML CLI tool with macOS binaries for Intel and Apple Silicon." \
            --verify-tag \
            artifacts/fdml-x86_64-apple-darwin/fdml-x86_64-apple-darwin.tar.gz \
            artifacts/fdml-aarch64-apple-darwin/fdml-aarch64-apple-darwin.tar.gz